#!/bin/bash
set -ueo pipefail

PEERS=${PEERS:-}
CLUSTERNAME=${CLUSTERNAME:-galera}
MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-}

run(){
	chown -R mysql: /var/lib/mysql
	exec /usr/sbin/mysqld \
	--basedir=/usr \
	--datadir=/var/lib/mysql \
	--plugin-dir=/usr/lib/mysql/plugin \
	--user=mysql \
	--console \
	--pid-file=/var/run/mysqld/mysqld.pid \
	--socket=/var/run/mysqld/mysqld.sock \
	--port=3306 \
	--wsrep_start_position=00000000-0000-0000-0000-000000000000:-1
}

if [ "${1:-}" = "garbd" ]; then
	exec garbd --group "${CLUSTERNAME}" "$@"
fi

if [ -e /etc/mysql/conf.d/runtime.cnf ]; then
	# This is our first run.
	run
fi

if [ -z "$PEERS" ]; then
	echo "PEERS undefined, this node is starting in bootstrap mode."
fi

[ ! -d /var/log/mysql ] && mkdir -pv /var/log/mysql
chown mysql:mysql -R /var/log/mysql

cat > /etc/mysql/conf.d/runtime.cnf << dog
[mysqld]
bind-address=0.0.0.0
wsrep_cluster_name="${CLUSTERNAME}"
wsrep_cluster_address=gcomm://$PEERS
wsrep_provider=/usr/lib/galera/libgalera_smm.so
dog

if [ -n "${BUFFER_POOL_SIZE:-}" ]; then
	echo "innodb_buffer_pool_size=\"$BUFFER_POOL_SIZE\"" >> /etc/mysql/conf.d/runtime.cnf
fi

if [ -n "$MYSQL_ROOT_PASSWORD" ]; then
	echo "Setting root password"
	run 2>/dev/null >/dev/null &
	until mysql -e "GRANT ALL PRIVILEGES on *.* to root@\"%\" \
		IDENTIFIED BY '${MYSQL_ROOT_PASSWORD}' \
		WITH \
		GRANT OPTION MAX_QUERIES_PER_HOUR 0 \
		MAX_CONNECTIONS_PER_HOUR 0 \
		MAX_UPDATES_PER_HOUR 0 \
		MAX_USER_CONNECTIONS 0; \
		flush privileges;"; do \
		printf "."
		sleep 2;
	done
	echo "done"
	echo "Root password set"
	killall mysqld
	while pgrep mysqld >/dev/null; do
		printf "."
		sleep 2
	done
	echo "done"
fi

#garbd --daemon --address gcomm://127.0.0.1:4567 --group "my_wsrep_cluster" -o gmcast.listen_addr tcp://127.0.0.1:4568

run
